### PR TITLE
Add basic CI for current Python and Django versions

### PR DESCRIPTION
**Pull request by allanlewis**
This PR updates the CI to build against current versions of Python and Django.

The Travis integration is currently broken: maintainers, you'll need to follow the steps here to get it working: https://docs.travis-ci.com/user/migrate/open-source-repository-migration
Then you'll need to do something like `git commit --amend --no-edit && git push -f` to trigger it.

I've tested the CI config on my fork - see allanlewis/django-username-email#1.

### CODE REVIEW

**Comment by allanlewis** [comment]
Updated after Django 4 changes.

**Comment by ataylor32** [comment]
@allanlewis Thanks for taking the time to do this!

@tmm Do you think you would be able to migrate the repo to travis-ci.com sometime?

**Comment by tmm** [comment]
@allanlewis nice one! @ataylor32 will do.

**Comment by allanlewis** [comment]
Thanks, all - glad I've been able to contribute in a small way 😊 

That said, I can't see a build from this repo for the merge...

**Comment by ataylor32** [comment]
@allanlewis I am the owner of this project now (@tmm transferred it to me). I don't have a plan on travis-ci.com. There is a free trial plan, but not a free plan. Would you be open to modifying your code to use GitHub Actions instead of Travis CI?

**Comment by allanlewis** [comment]
Sure, I've started work on this here: https://github.com/ataylor32/django-username-email/compare/allanlewis:migrate-ci-to-github-actions

**Comment by allanlewis** [comment]
See #25.

**Pull request merged**
