### PR TITLE
Move AbstractCUser and CUserManagers to separate files

### PR DESCRIPTION
**Pull request by vryazanov**
Hi,
I've faced with the issue when I tried to use AbstractCUser as a base class for a custom model. Django raises an exception which is related to reverse accessor. The error looks like:
```
core.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'CUser.groups'.
HINT: Add or change a related_name argument to the definition for 'User.groups' or 'CUser.groups'.
```
and etc.

### CODE REVIEW

**Comment by ataylor32** [comment]
Thanks for the contribution! The dev branch just got merged into the master branch. It was a pretty major refactoring. The problem shouldn't happen anymore.

**Comment by vryazanov** [comment]
@ataylor32  when are you going to push master branch?  As I can see the problem haven't relosved yet.

**Comment by ataylor32** [comment]
The master branch is already up-to-date. When you tested, how did you upgrade your copy of django-username-email? Did you `pip install` from PyPI or GitHub? PyPI does not yet have the latest version. That's something that I can't do; it will have to be done by @tmm when he has the time.

**Comment by vryazanov** [comment]
I did upgrade from GitHub. I think we aren't on the same page. In code I do something like this:
```
from cuser.models import AbstractCUser

class User(AbstractCUser):
    pass
```
and in this case ```makemigrations``` does not work properly. It tries to create migrations for CUser model from packages and User from models.py, but they have the same reverse accessor. It won't work too if remove cuser from INSTALLED_APPS.

**Comment by tmm** [comment]
@VRyazanov The latest version will be on PyPi soon. Is this still an issue? cc: @ataylor32

**Comment by ataylor32** [comment]
@VRyazanov I was doing something wrong when I tried to reproduce the issue. I tried again and was able to reproduce it. I fixed it in 5d4b43d . Thanks for the pull request!

**Comment by vryazanov** [comment]
@ataylor32 tnx a lot, I didn't know about ```swappable``` before this moment

**Pull request closed without merging**
